name: SonarCloud Scan

on:
  workflow_dispatch:
    # Esto permite que el flujo de trabajo se ejecute manualmente desde GitHub

jobs:
  SonarCloudScan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=GuillermoW7_Scorpion-portfolio
            -Dsonar.organization=guillermow7
            -Dsonar.sources=.
            -Dsonar.host.url=https://sonarcloud.io
