name: SonarCloud Scan

on:
  push:
    branches:
      - main  # Ajusta esta rama según tu configuración

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.1.1
        with:
          args: |
            -Dsonar.projectKey=GuillermoW7_Scorpion-portfolio
            -Dsonar.organization=guillermow7
            -Dsonar.sources=.
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
